### ISSUE TITLE
アルゴリズム入門１

### ISSUE THREAD

**Issue by dsaa151562000** [DiveintoCode-corp/ai-course#39]

**Comment by dsaa151562000** [comment]
二部探索

import math

list = range(100)
target_number = 42

low_number = 0
high_number = len(list)

while (low_number != high_number):
    n += 1
    print("{}回目の探索です".format(n))
    center_number = math.floor((low_number + high_number) / 2)
    if (list[center_number] < target_number):
        low_number = center_number + 1
    elif (target_number < list[center_number]):
        high_number = center_number - 1
    else:
        break

実行でNameError: が発生　n
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    n += 1
NameError: name 'n' is not defined

実行でTypeError:  が発生
list indices must be integers, not float
-------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 112, in <module>
    if (list[center_number] < target_number):
TypeError: list indices must be integers, not float
